//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int RSN { get; set; }
        public int UserID { get; set; }
        public Nullable<int> GuestID { get; set; }
        public System.DateTime BookingDTime { get; set; }
        public string GuestDTime { get; set; }
        public string Token { get; set; }
        public string SessionTitle { get; set; }
        public string SessionID { get; set; }
        public string Live { get; set; }
        public string isDone { get; set; }
    }
}
