//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Confirms = new HashSet<Confirm>();
        }

        public int Id { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string FName { get; set; }
        [Required]
        [Display(Name = "Last Name")]
        public string LName { get; set; }
        [Required]
        [Display(Name = "User Name")]
        public string Username { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "E-mail")]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }
        [Display(Name = "Country")]
        public int CountryID { get; set; }
        [Required]
        [DataType(DataType.Date)]

        public System.DateTime DOB { get; set; }
        [Display(Name = "Nationality")]
        public int NationalityID { get; set; }
        [Required]
        public string Gender { get; set; }
        [Display(Name = "Job")]
        public int JobCode { get; set; }
        [Display(Name = "Admin ?")]
        public bool isAdmin { get; set; }
        [Required]
        [Display(Name = "School")]
        public string SchoolName { get; set; }
        [Required]
        [Display(Name = "Time zone")]
        public string TimeZone { get; set; }
        [Required]
        [Display(Name = "Device Token")]
        public string DeviceToken { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Confirm> Confirms { get; set; }
        public virtual Country Country { get; set; }
        public virtual Job Job { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
